#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinately. with a sleep 2 between each iteration.

trap "echo I hate the kill command && rm -f /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -f /var/run/myscript.pid ; exit" SIGQUIT

i=true

echo $$ > /var/run/myscript.pid

while [ $i ]
do
  echo "To infinity and beyond"
  sleep 2
done
