#!/usr/bin/env bash
# init script to start, restart and stop manage_my_process process

trap 'check_and_exit "$option"' SIGTERM
start_cmd="./manage_my_process"
option="$1"


function check_and_exit() {
	if [ "$1" == 'restart' ]
	then
		eval "$start_cmd" &
		echo $(( "$!" + 1 )) > /var/run/my_process.pid
		echo manage_my_process restarted
	fi
	exit
}

if [ "$1" == 'start' ]
then
	eval "$start_cmd" &
	echo manage_my_process started
	echo "$(( $! + 1 ))" > /var/run/my_process.pid
elif [ "$1" == 'stop' ]
then
	rm -f /var/run/my_process.pid
	echo manage_my_process stopped
	kill "$(pgrep -f manage_my_process)"
elif [ "$1" == 'restart' ]
then
	pkill -f manage_my_process
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
