#!/usr/bin/env bash
# This script is displays "Best School" 10 times
# If it reaches the 9 iteration it displays "Hi" in addition to "Best School"
# on two separate lines

n=0
while [ $n -lt 10 ];
do
	if [ $n -eq 8 ]
	then
		echo Best School
		echo Hi
		((n++))
		continue
	fi
	echo Best School
	((n++))
done
